# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx2G

# Fabric Properties
minecraft_version = 26.1
loader_version = 0.18.5
loom_version = 1.15-SNAPSHOT

# Mod Properties
mod_version = 0.3.0-alpha
maven_group = com.dashomi
archives_base_name = ActionRegulator

# Dependencies
fabric_api_version = 0.144.3+26.1
modmenu_version = 18.0.0-alpha.8
owo_version = 0.13.0+26.1